---
title: "RNA folding and design: An AI Driven Approach"
author: "蔡祎涛"
date: "2025-10-26"
categories: [RNA, AI]
---
### RNA language model for RNA folding and design

RNA folding and design are fundamental problems which are essential for understanding RNA functions and drug design. For RNA folding, the real world datasets are very biased, due to few RNA families like tRNA(transfer RNA) or rRNA(ribosome RNA) etc., but the possible structures of any RNA sequences can be folded into are enormous compare to the human curated RNA datasets. We tried to avoid such bias by using synthetic datasets generated by ViennaRNA. For RNA design, synthetic datasets are common choice.  

Currently, most of the AI models are either specifically designed for RNA folding task or RNA design task. We find that it is beneficial to unify the two tasks using a general language model framework, in this way we can boost the performance of the model for both tasks. We also find that reinforcement learning can significantly improve the performance of the language model on RNA design task.

### 数学公式展示

我们可以轻松地写出 LaTeX 公式，比如麦克斯韦方程组：

$$
\nabla \cdot \mathbf{E} = \frac{\rho}{\varepsilon_0} \\
\nabla \cdot \mathbf{B} = 0 \\
\nabla \times \mathbf{E} = -\frac{\partial \mathbf{B}}{\partial t} \\
\nabla \times \mathbf{B} = \mu_0 \left( \mathbf{J} + \varepsilon_0 \frac{\partial \mathbf{E}}{\partial t} \right)
$$

### 交互式滑块

下面是一个用 [Observable JS](https://observablehq.com/) 制作的交互式滑块。拖动它，下面的文字会实时更新！

```{ojs}
// 使用 viewof 关键字创建一个滑块，它的值会绑定到变量 x
viewof x = Inputs.range(, {label: "选择一个值", step: 1, value: 30})